codecov:
  require_ci_to_pass: true
  
comment: false

coverage:
  status:
    project:
      default:
        target: 20%
    patch: false

github_checks:
    annotations: false

ignore:
  - tests
  - docs
