TrapemaxCtcCal:
  ylabel: "Energy diff / keV"
  colors:
    - dodgerblue
    - b
  percentage: true
  title: "pulser_stab"
  unit: "keV"
  limits:
    - null
    - null

Trapemax:
  ylabel: "Energy diff / keV"
  colors:
    - dodgerblue
    - b
  percentage: true
  title: "pulser_stab_uncalib"
  unit: "%"
  limits:
    - null
    - null

Baseline:
  ylabel: "Baseline % variations"
  colors:
    - r
    - firebrick
  percentage: true
  title: "baseln_stab"
  unit: "%"
  limits:
    - -10
    - 10

BlStd:
  ylabel: "Baseline std [ADC]"
  colors:
    - peru
    - saddlebrown
  percentage: false
  title: "baseln_spike"
  unit: "ADC"
  limits:
    - null
    - 50

FEP_variation:
  ylabel: "FEP gain variation [keV]"
  colors:
    - peru
    - saddlebrown
  percentage: false
  title: "FEP_gain_stab"
  unit: "keV"
  limits:
    - null
    - null

tot_discharge_dead_time:
  title: "tot_discharge_dead_time"
  unit: "%"
  limits:
    - null
    - 0.02

IsDischarge:
  title: "discharge_rate"
  unit: "mHz"
  limits:
    - null
    - 5

IsSaturated:
  title: "saturated_rate"
  unit: "mHz"
  limits:
    - null
    - 5
