output: "<to be set by script>"

dataset:
  experiment: "L200"
  period: "<to be set by script>"
  version: "<to be set by script>"
  path: "<to be set by script>"
  type: "phy"
  runs: "<to be set by script>"  # int(run.split("r")[-1])

scdb:
  saving: "overwrite"
  slow_control:
    parameters:
      - DaqLeft-Temp1
      - DaqLeft-Temp2
      - DaqRight-Temp1
      - DaqRight-Temp2
      - RREiT
      - RRNTe
      - RRSTe
      - ZUL_T_RR


my_config:
  saving: "append"
  subsystems:
    geds:
      "Event rate in pulser events":
        parameters: event_rate
        event_type: pulser
        plot_structure: per string
        resampled: only
        plot_style: vs time
        time_window: 20S

      "Event rate in FCbsln events":
        parameters: event_rate
        event_type: FCbsln
        plot_structure: per string
        resampled: only
        plot_style: vs time
        time_window: 20S

      "Baselines (dsp/baseline) in pulser events":
        parameters: baseline
        event_type: pulser
        plot_structure: per string
        resampled: only
        plot_style: vs time
        AUX_ratio: true
        variation: true
        time_window: 10T

      "Baselines (dsp/baseline) in FCbsln events":
        parameters: baseline
        event_type: FCbsln
        plot_structure: per string
        resampled: only
        plot_style: vs time
        variation: true
        time_window: 10T

      "Mean baselines (dsp/bl_mean) in pulser events":
        parameters: bl_mean
        event_type: pulser
        plot_structure: per string
        resampled: only
        plot_style: vs time
        AUX_ratio: true
        variation: true
        time_window: 10T

      "Mean baselines (dsp/bl_mean) in FCbsln events":
        parameters: bl_mean
        event_type: FCbsln
        plot_structure: per string
        resampled: only
        plot_style: vs time
        variation: true
        time_window: 10T

      "Uncalibrated gain (dsp/trapEmax) in pulser events":
        parameters: trapEmax
        event_type: pulser
        plot_structure: per string
        resampled: only
        plot_style: vs time
        AUX_ratio: true
        variation: true
        time_window: 10T

      "Uncalibrated gain (dsp/trapEmax) in FCbsln events":
        parameters: trapEmax
        event_type: FCbsln
        plot_structure: per string
        resampled: only
        plot_style: vs time
        AUX_ratio: true
        variation: true
        time_window: 10T

      "Calibrated gain (hit/trapEmax_ctc_cal) in pulser events":
        parameters: trapEmax_ctc_cal
        event_type: pulser
        plot_structure: per string
        resampled: only
        plot_style: vs time
        variation: true
        time_window: 10T

      "Calibrated gain (hit/trapEmax_ctc_cal) in FCbsln events":
        parameters: trapEmax_ctc_cal
        event_type: FCbsln
        plot_structure: per string
        resampled: only
        plot_style: vs time
        variation: true
        time_window: 10T

      "Noise (dsp/bl_std) in pulser events":
        parameters: bl_std
        event_type: pulser
        plot_structure: per string
        resampled: only
        plot_style: vs time
        AUX_ratio: true
        variation: true
        time_window: 10T

      "Noise (dsp/bl_std) in FCbsln events":
        parameters: bl_std
        event_type: FCbsln
        plot_structure: per string
        resampled: only
        plot_style: vs time
        AUX_ratio: true
        variation: true
        time_window: 10T

      "A/E (from dsp) in pulser events":
        parameters: AoE_Custom
        event_type: pulser
        plot_structure: per string
        resampled: only
        plot_style: vs time
        variation: true
        time_window: 10T

      "A/E (from dsp) in FCbsln events":
        parameters: AoE_Custom
        event_type: FCbsln
        plot_structure: per string
        resampled: only
        plot_style: vs time
        variation: true
        time_window: 10T

      "Quality cuts in physics events":
        parameters: quality_cuts
        event_type: phy
        qc_flags: true
        qc_classifiers: false
